# Generated by Django 5.1.7 on 2025-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_quiz_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='brand',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='createAt',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='rating',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
